services:
  - type: web
    name: truthlens-fnd
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader punkt stopwords wordnet omw-1.4
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
